name: 'shopops'
version: '1.0.0'
profile: 'shopops'

models:
  shopops:
    # 1. Couche Staging (Vues virtuelles)
    staging:
      +materialized: view

    # 2. Couche Intermediate (Vues virtuelles)
    intermediate:
      +materialized: view

    # 3. Couche Marts (Tables physiques Iceberg)
    marts:
      +materialized: table
      +table_type: iceberg

# Configuration des tests
tests:
  # Activé par défaut pour tout le projet (parfait pour le Staging)
  +store_failures: true
  +schema: "audit_data_quality"

  shopops:
    marts:
      # On le désactive spécifiquement pour la couche finale pour éviter le conflit Iceberg
      +store_failures: false
