repos:
  # 1. Vérifications basiques de Git (hygiène du texte)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  # 2. Formatage automatique du code Terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.1
    hooks:
      - id: terraform_fmt
